#!/bin/sh
# dropbox service
# Replace with linux users you want to run Dropbox clients for

VERSION=`cat /root/.dropbox-dist/VERSION`
DAEMON=/root/.dropbox-dist/dropbox-lnx.x86_64-$VERSION/dropbox

start() {
  echo "Starting dropbox..."
  if [ -x $DAEMON ]; then
  HOME=/root start-stop-daemon -b -o -c root -S -u root -x $DAEMON
  fi
}

stop() {
  echo "Stopping dropbox..."
  if [ -x $DAEMON ]; then
  start-stop-daemon -o -c root -K -u root -x $DAEMON
  fi
}

case "$1" in
  start)
  start
  ;;
  stop)
  stop
  ;;
  restart|reload|force-reload)
  stop
  start
  ;;
  *)
  echo "Usage: /etc/init.d/dropbox {start|stop|reload|force-reload|restart}"
  exit 1
  esac

exit 0
